### ISSUE TITLE
Security Sandbox Violation

### ISSUE THREAD

**Issue by javicebrian** [denisdanielyan/as3-Application-Only-Twitter#5]
Hi mate,

thanks for suck a great work but when deploying i'm getting the following error:
Error #2044: Unhandled securityError:. text=Error #2048: Security sandbox violation

is it just me or is a known error?

thanks!

**Comment by denisdanielyan** [comment]
First, sorry for the late reply.
What you are seeing is caused by a missing cross-domain-policy file at twitter. 
Which means, you are doing something wrong as twitter will never post such a file. 
To be honest, I never testet the module as a Web project and probably never will. 
So I am sorry but I am not able to help you out here.
